---
- name: set SSH MaxSessions to 50
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: 'MaxSessions'
    line: 'MaxSessions 50'
  register: maxsessions
- name: set SSH ClientAliveInterval to 0
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: 'ClientAliveInterval'
    line: 'ClientAliveInterval 0'
  register: clientaliveinterval
- name: set SSH ClientAliveCountMax to 0
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: 'ClientAliveCountMax'
    line: 'ClientAliveCountMax 0'
  register: clientalivecountmax
- name: restart SSH daemon
  service:
    name: sshd
    state: restarted
  when: maxsessions.changed or clientaliveinterval.changed or clientalivecountmax.changed
