---
- name: add Oracle key 1
  apt_key:
    url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
    state: present
- name: add Oracle key 2
  apt_key:
    url: https://www.virtualbox.org/download/oracle_vbox.asc
    state: present
- name: add vbox repo
  apt_repository:
    repo: deb http://download.virtualbox.org/virtualbox/debian "{{ubuntu_version}}" contrib
    state: present
- include_role:
    name: apt-lock-wait
- name: install vbox
  apt:
    name: virtualbox-5.2
    state: present
